### PR TITLE
Fix edit election page to match new alternatives styles

### LINKED ISSUE #383: Redesign election admin view
This could use an overhaul after the recent changes

image

### PR DESCRIPTION
**Pull request by LudvigHz**
closes #383 

Fixes admin edit election page to look like it should with the style changes added.
- Also makes the access code a little more visible
- And adds a little gimmick to copy the access code with an icon/button :grin:.

image

### CODE REVIEW

File: client/controllers/editElectionCtrl.js [hunk 1]
```diff
@@ -139,5 +139,21 @@ module.exports = [
         .path('/admin/create_election')
         .search({ election: JSON.stringify(election) });
     };
+
+    $scope.copyToClipboard = function (text) {
```
Comment (SmithPeder) [inline client/controllers/editElectionCtrl.js:143]: > gimmick to copy the access code with an icon/button

😎 Cool. Kinda `lol` code, but I'll allow it 👍🏻

**Review by SmithPeder — APPROVED** [review]
👍🏻

File: client/controllers/editElectionCtrl.js (hunk 1 above)
Comment (LudvigHz) [reply client/controllers/editElectionCtrl.js:143]: Yeee, but it is the way to do it :laughing:.
